/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#ifndef _JERRYSCRIPT_MBED_LIB_GROVEEARBUDSENSOR_H
#define _JERRYSCRIPT_MBED_LIB_GROVEEARBUDSENSOR_H

#include "mbed-js-groveearbudsensor/mbed-js-groveearbudsensor.h"
#include "jerryscript-mbed-library-registry/wrap_tools.h"

void mbed_js_GroveEarbudSensor_setup();

DECLARE_JS_WRAPPER_REGISTRATION (groveearbudsensor)
{
    REGISTER_CLASS_CONSTRUCTOR(GroveEarbudSensor);
    mbed_js_GroveEarbudSensor_setup();
}

#endif // _JERRYSCRIPT_MBED_LIB_GROVEEARBUDSENSOR_H
