/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#ifndef _JERRYSCRIPT_MBED_GROVEEARBUDSENSOR_H
#define _JERRYSCRIPT_MBED_GROVEEARBUDSENSOR_H

#include "jerryscript-mbed-library-registry/wrap_tools.h"

#include "GroveEarbudSensor.h"

DECLARE_CLASS_CONSTRUCTOR(GroveEarbudSensor);
jerry_value_t mbed_js_wrap_native_object(GroveEarbudSensor* ptr);

#endif // _JERRYSCRIPT_MBED_GROVEEARBUDSENSOR_H
